---
title: "Verificação de casos no Painel Covid-19 que são óbitos no SIVEP"
author: "Centro de informações estratégicas em vigilância em saúde - CIEVS"
date: "13/04/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE}
# Casos no painel e óbitos no SIVEP Gripe 

# PACOTES -----------------------------------------------------------------

rm(list=ls())
gc()

if (!require("pacman")) install.packages("pacman")
pacman::p_load(tidyverse, lubridate, tibbletime, dplyr, data.table, epitools, sf, knitr, xlsx, openxlsx, read.dbc, DBI, odbc)
```


```{r, include=FALSE}
# BANCOS UTILIZADOS -------------------------------------------------------

hoje <- Sys.Date()
hoje <- format(hoje, "%d-%m-%Y")

# Sivep
dados22 <- openxlsx::read.xlsx("//srv-fs/COVID_DIVEP/ÓBITOS/LAUDOS E SÍNTESES DIÁRIAS/2022/SIVEP 2022.xlsx")
dados22 <- dados22 %>% filter(CO_MUN_NOT == 530010)
dados22 <- dados22 %>% mutate(NU_CPF = gsub(pattern = "[,]|-|[.]|;| |^0+", replacement = "", x = NU_CPF, perl = T))

```


```{r, include=FALSE}
# Painel
con <- dbConnect(odbc::odbc(), 
                 Driver = "SQL Server", 
                 server = '10.91.254.32',
                 database='controle_corona',
                 uid = 'user_Saude_02',
                 pwd = 'ses@1974',
                 encoding = "WINDOWS-1252")
res <- dbSendQuery(con, 'SELECT id, nomecompletoPaciente, dataNascimentoFull, mae, cpf, dataObito, enderecoCompleto, RA, cep, dataCadastro FROM View_Completa_saude')
dado <- dbFetch(res)
painel<- as_tibble(dado)
rm(dado)
```

```{r, include=FALSE}
# Configurações do painel
painel$dataNascimentoFull <-  as.Date(painel$dataNascimentoFull , "%Y-%m-%d")
painel$dataNascimentoFull <- format(painel$dataNascimentoFull, "%d/%m/%Y")
painel <- painel %>% mutate(cpf = gsub(pattern = "[,]|-|[.]|;| |^0+", replacement = "", x = cpf, perl = T))
painel <- painel %>% mutate(cpf  = ifelse(cpf  == " " | cpf == "" | cpf  == "  ", NA, cpf ))

# Filtrando o ano de 2022
hoje2 <- Sys.Date()
anoHoje <- format(hoje2,"%Y")

painel <- as_tbl_time(painel, index = dataCadastro) #transformando a data novamente
DataOrdenadaObt <- painelDataObt[order(painelDataObt$dataObt),] #ordenando a data
painelFiltroAnoObt <- filter_time(DataOrdenadaObt, ~ anoHoje) #filtrando somente ano de 'anoHoje'
```

```{r, include=FALSE}
# Ajustando as RAs dos bancos ---------------------------------------------
dados22$RAs_SIVEP <- (dados22$ID_MN_RESI)
painel$RAs_PAINEL <- (painel$RA)

painel <- painel %>%
  mutate(nomecompletoPaciente = toupper(nomecompletoPaciente),
         nomecompletoPaciente = str_replace_all(nomecompletoPaciente, "[[:punct:]]", ""),
         nomecompletoPaciente = chartr("ÁÂÉÈÀÔÎÍÃÕÓÚÇ", "AAEEAOIIAOOUC", nomecompletoPaciente),
         nomecompletoPaciente = str_squish(nomecompletoPaciente))

dados22 <- dados22 %>%
  mutate(NM_PACIENT = toupper(NM_PACIENT),
         NM_PACIENT = str_replace_all(NM_PACIENT, "[[:punct:]]", ""),
         NM_PACIENT = chartr("ÁÂÉÈÀÔÎÍÃÕÓÚÇ", "AAEEAOIIAOOUC", NM_PACIENT),
         NM_PACIENT = str_squish(NM_PACIENT))

painel <- painel %>%
  mutate(RAs_PAINEL = toupper(RAs_PAINEL),
         RAs_PAINEL = str_replace_all(RAs_PAINEL, "[[:punct:]]", ""),
         RAs_PAINEL =chartr("ÁÂÉÈÀÔÎÍÃÕÓÚÇ", "AAEEAOIIAOOUC", RAs_PAINEL),
         RAs_PAINEL = str_squish(RAs_PAINEL))

dados22 <- dados22 %>%
  mutate(RAs_SIVEP = toupper(RAs_SIVEP),
         RAs_SIVEP = str_replace_all(RAs_SIVEP, "[[:punct:]]", ""),
         RAs_SIVEP =chartr("ÁÂÉÈÀÔÎÍÃÕÓÚÇ", "AAEEAOIIAOOUC", RAs_SIVEP),
         RAs_SIVEP = str_squish(RAs_SIVEP))
```


```{r, include=FALSE}
ras_sivep <- dados21 %>% select(NM_PACIENT, DT_NASC, NU_NOTIFIC, ID_MN_RESI, RAs_SIVEP, NU_CPF, NM_MAE_PAC, NM_LOGRADO, NU_CEP)
ras_sivep <- ras_sivep %>% mutate(RAs_SIVEP = str_replace_all(RAs_SIVEP, "BRASILIA*", "PLANO PILOTO")) %>% mutate(RAs_SIVEP = str_replace_all(RAs_SIVEP, "ASA SUL|ASA NORTE", ""), RAs_SIVEP = str_squish(RAs_SIVEP))
```


```{r, include=FALSE}
# Criando a chave
painel <- painel %>% mutate(chave = paste0(nomecompletoPaciente, " ", dataNascimentoFull))
ras_sivep <- ras_sivep %>% mutate(chave = paste0(NM_PACIENT, " ", DT_NASC))
```


```{r, include=FALSE}
# Fazendo match do Painel com o Sivep
painel_sivep <- merge(painel, ras_sivep, by = "chave")

# Mantendo apenas os diferentes
painel_sivep <- painel_sivep %>% mutate(RAs_iguais = ifelse(RAs_PAINEL == RAs_SIVEP, "sim", "não"))
painel_sivep <- painel_sivep %>% filter(RAs_iguais == "não")
```


```{r, include=FALSE}
# Banco final
final <- painel_sivep %>% select(P.Record_Id = Record_Id, P.nomecompletoPaciente = nomecompletoPaciente, P.dataNascimentoFull = dataNascimentoFull, S.DT_NASC = DT_NASC, P.mae = mae, S.NM_MAE_PAC = NM_MAE_PAC, P.cpf = cpf, S.NU_CPF = NU_CPF, P.enderecoCompleto = enderecoCompleto, S.NM_LOGRADO = NM_LOGRADO, P.RA = RA,  S.ID_MN_RESI = ID_MN_RESI, P.cep = cep, S.NU_CEP = NU_CEP, S.NU_NOTIFIC = NU_NOTIFIC)
final$P.cpf <- as.numeric(final$P.cpf)
final$S.NU_CPF<- as.numeric(final$S.NU_CPF)

final <- final %>% mutate(cpfs_iguais = ifelse(P.cpf == S.NU_CPF, "sim", "não"))
```


```{r, include=FALSE}
# Salvando
setwd("D:/RAs_PAINEL_SIVEP")
write.xlsx2(as.data.frame(final), paste0("RAs_Ouro__Painel_SIVEP_", hoje, ".xlsx"), sheetName = "2022", append=TRUE, row.names = F)
```

